"""game_id

Revision ID: f92557f15652
Revises: 78758cc702f4
Create Date: 2025-04-10 18:30:02.062320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f92557f15652'
down_revision: Union[str, None] = '78758cc702f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('game_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'questions', 'games', ['game_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_column('questions', 'game_id')
    # ### end Alembic commands ###
